services:
  car-price-predictor:
    image: nehastha/a3-car-price:latest
    container_name: car-price-predictor
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:8050"
    volumes:
      - ./app:/root/app
      - ./.vscode-server:/root/.vscode-server
