name: A3 CICD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to project repository
      uses: actions/checkout@v3


    - name: Python environment setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'


    - name: Install dependencies for project
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Execute unit tests
      run: |
        pytest

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout to project repository
      uses: actions/checkout@v3

    - name: Authenticate with DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build docker image for deployment
      run: docker build -t nehastha/a3-car-price:latest .

    - name: Push docker image to dockerhub
      run: docker push nehastha/a3-car-price:latest

    - name: Configure SSH and docker settings
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/st124963
        chmod 600 ~/.ssh/st124963

        cat << 'EOF' > ~/.ssh/config
        Host bazooka
          HostName bazooka.cs.ait.ac.th
          User st124963
          IdentityFile ~/.ssh/st124963

        Host ml2023
          HostName ml.brain.cs.ait.ac.th
          User st124963
          IdentityFile ~/.ssh/st124963
          ProxyJump bazooka
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
        EOF
        chmod 600 ~/.ssh/config

        ssh-keyscan -p 22 -H bazooka.cs.ait.ac.th >> ~/.ssh/known_hosts 2>/dev/null 
        chmod 600 ~/.ssh/known_hosts

    - name: Deploy to ml2025
      run: |
        ssh -v st124963@ml2023 << 'EOF'
        cd st124963A3/
        docker compose down
        docker compose up --pull always -d
        EOF